version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - app-network
    restart: unless-stopped
    container_name: mindmesh-backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: mindmesh-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api

networks:
  app-network:
    driver: bridge
